#!/bin/bash 
if [[ $# -ne 1 ]]; then
	echo "USE : genFile [FILENAME]"
	exit 1;
fi

echo "Lorem ipsum dolor sit amet, cu qui hinc prompta necessitatibus, est ea omnium argumentum, elit movet percipitur qui an. Mediocrem evertitur qui eu, vim in vero omnium luptatum, unum nobis impetus ad mel. Eam at aliquando liberavisse. Mel te possit moderatius, malorum persius nusquam has ea.

His blandit inciderint te. Te salutandi incorrupte qui. Vix no consul percipitur, id eos ignota labore fabellas. Ex pri mucius laoreet. Sit et partem erroribus torquatos. In cibo vidisse eos.

Noluisse quaerendum mei ad, facilisi facilisis mel an. In mei illum animal maiestatis. Insolens reformidans ne duo, duo justo admodum pertinax ei, nec iriure accusam expetenda id. Nibh decore eam in, nec tantas nostrud admodum te. Nec ne habeo omittam percipit.

Pro te debitis volumus tincidunt, sea at facilis instructior. Velit corpora usu cu. Admodum corpora lucilius vis in. Mei an lorem ubique, est quidam praesent et.

Odio gubergren in sed, ea vel primis delenit interpretaris. Ut nostrud constituam ullamcorper sea. Purto munere nec ea, dicta solet congue usu ex, vis delenit detraxit eu. Choro nominavi cu eam, diam movet vidisse per in. Ei sea tantas omittantur." > $1
